In [1]:
time = [0, 1, 2, 3, 4, 5]
temperature = [32, 35, 38, 40, 42, 45]
voltage = [400, 395, 390, 385, 380, 375]
current = [20, 22, 25, 28, 30, 32]
charge = [95, 88, 80, 70, 60, 48]

In [2]:
for i in range(6):
    print(time[i], temperature[i], voltage[i], current[i], charge[i])

0 32 400 20 95
1 35 395 22 88
2 38 390 25 80
3 40 385 28 70
4 42 380 30 60
5 45 375 32 48


In [3]:
for i in range(6):
    if temperature[i] > 40:
        print("High Temperature Alert")
    else:
        print("Temperature Normal")

Temperature Normal
Temperature Normal
Temperature Normal
Temperature Normal
High Temperature Alert
High Temperature Alert


In [4]:
for i in range(6):
    if charge[i] < 50:
        print("Low Battery Alert")
    else:
        print("Battery Charge Normal")

Battery Charge Normal
Battery Charge Normal
Battery Charge Normal
Battery Charge Normal
Battery Charge Normal
Low Battery Alert


In [5]:
def battery_status(c):
    if c > 70:
        return "High"
    elif c >= 50:
        return "Medium"
    else:
        return "Low"

print(battery_status(95))
print(battery_status(60))
print(battery_status(48))

High
Medium
Low


In [6]:
import numpy as np

D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

In [7]:
print("Shape:", D.shape)

Shape: (6, 4)


In [8]:
print("Average temperature:", np.mean(D[:, 0]))
print("Average voltage:", np.mean(D[:, 1]))
print("Average current:", np.mean(D[:, 2]))
print("Average charge:", np.mean(D[:, 3]))

Average temperature: 38.666666666666664
Average voltage: 387.5
Average current: 26.166666666666668
Average charge: 73.5


In [9]:
print("Maximum temperature:", np.max(D[:, 0]))
print("Minimum temperature:", np.min(D[:, 0]))

Maximum temperature: 45
Minimum temperature: 32


In [10]:
voltage = D[:, 1]
print("Voltage:", voltage)

Voltage: [400 395 390 385 380 375]


In [11]:
print(D[D[:, 0] > 40])

[[ 42 380  30  60]
 [ 45 375  32  48]]


In [12]:
print(D[D[:, 3] < 50])

[[ 45 375  32  48]]


In [13]:
A = np.array([[2, 1],
              [1, 3]])

X = np.array([40, 25])

Y = A @ X

print("Y:", Y)

Y: [105 115]


In [14]:
print("Transpose:")
print(A.T)

Transpose:
[[2 1]
 [1 3]]


In [15]:
print("Determinant:", np.linalg.det(A))

Determinant: 5.000000000000001


In [16]:
print("Inverse:")
print(np.linalg.inv(A))

Inverse:
[[ 0.6 -0.2]
 [-0.2  0.4]]


In [17]:
A = np.array([[2, 1],
              [1, 3]])

B = np.array([100, 120])

answer = np.linalg.solve(A, B)

print("x and y:", answer)

x and y: [36. 28.]


In [18]:
def rate(t):
    return -2 - t

print("Rate at t=2:", rate(2))
print("Rate at t=5:", rate(5))

Rate at t=2: -4
Rate at t=5: -7
