In [5]:
import numpy as np
arr = np.array([10, 20, 30])
print(arr)

[10 20 30]


In [6]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
arr = np.arange(0,12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
arr = np.arange(0,12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)
print(arr.size)

In [ ]:
arr = np.linspace(1, 10, 5)
print(arr)

In [ ]:
arr = np.eye(4)
print(arr)

In [ ]:
arr = np.full((3, 4), 7)
print(arr)

In [ ]:
arr = np.array([[10, 20, 30],[40, 50, 60]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

In [ ]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr)
print(arr.ndim)   # Number of dimensions
print(arr.shape)  # (Layers, Rows, Columns)
print(arr.size)   # Total number of elements
print(arr[0])        # First layer
print(arr[1])        # Second layer
print(arr[0][1])     # Second row of first layer
print(arr[1][0][0])  # Element 9

In [15]:
import numpy as np
arr = np.array([7,8,9,10,11,12,])
new_arr = arr.reshape(3,2)
print(new_arr)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [16]:
arr = np.array([7,8,9,10,11,12])
new_arr_1 = np.reshape(arr,(3,2))
print(new_arr_1)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [23]:
arr_3d = np.array([9,10,11,12,13,14,15,16])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

[[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [24]:
import numpy as np

arr = np.array([5, 15, 25, 35, 45, 55])

print(arr[1:5])

print(arr[:4])

print(arr[2:])

print(arr[::2])

[15 25 35 45]
[ 5 15 25 35]
[25 35 45 55]
[ 5 25 45]


In [25]:
import numpy as np

arr = np.array([[5, 15, 25],
                [35, 45, 55],
                [65, 75, 85]])

print(arr[0:2,1:3])

print(arr[1,:])

print(arr[:,2])

[[15 25]
 [45 55]]
[35 45 55]
[25 55 85]


In [26]:
import numpy as np

arr = np.array([
    [[2, 4, 6], [8, 10, 12]],
    [[14, 16, 18], [20, 22, 24]]
])

print(arr[0,:,:])

print(arr[1,1,:])

print(arr[:,:,0])

[[ 2  4  6]
 [ 8 10 12]]
[20 22 24]
[[ 2  8]
 [14 20]]


In [27]:
import numpy as np

a = np.array([15, 25, 35])

b = np.array([3, 5, 7])

print("Addition:", a+b)

print("Subtraction:", a-b)

print("Multiplication:", a*b)

print("Division:", a/b)

print("Floor Division:", a//b)

print("Modulus:", a%b)

print("Power:", a**2)

Addition: [18 30 42]
Subtraction: [12 20 28]
Multiplication: [ 45 125 245]
Division: [5. 5. 5.]
Floor Division: [5 5 5]
Modulus: [0 0 0]
Power: [ 225  625 1225]


In [28]:
import numpy as np

arr = np.array([4, 9, 16, 25, 36])
print("Original Array:", arr)

print("\nSquare Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Cube:", np.power(arr, 3))

arr2 = np.array([-6, -12, 18, -24, 30])
print("\nAbsolute Value:", np.abs(arr2))

print("\nExponential:", np.exp(arr))
print("\nNatural Log:", np.log(arr))
print("Log Base 10:", np.log10(arr))

print("\nSine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Tangent:", np.tan(arr))

decimal = np.array([3.45, 5.78, 7.23, 9.86])
print("\nRounded Values:", np.round(decimal))
print("Ceiling:", np.ceil(decimal))
print("Floor:", np.floor(decimal))

Original Array: [ 4  9 16 25 36]

Square Root: [2. 3. 4. 5. 6.]
Square: [  16   81  256  625 1296]
Cube: [   64   729  4096 15625 46656]

Absolute Value: [ 6 12 18 24 30]

Exponential: [5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10
 4.31123155e+15]

Natural Log: [1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]
Log Base 10: [0.60205999 0.95424251 1.20411998 1.39794001 1.5563025 ]

Sine: [-0.7568025   0.41211849 -0.28790332 -0.13235175 -0.99177885]
Cosine: [-0.65364362 -0.91113026 -0.95765948  0.99120281 -0.12796369]
Tangent: [ 1.15782128 -0.45231566  0.30063224 -0.13352641  7.75047091]

Rounded Values: [ 3.  6.  7. 10.]
Ceiling: [ 4.  6.  8. 10.]
Floor: [3. 5. 7. 9.]


In [29]:
import numpy as np

marks = np.array([65, 78, 92, 71, 85, 96, 80])

print("Original Array:", marks)

print("Sorted Array:", np.sort(marks))

print("\nSum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Range:", np.ptp(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))
print("Index of Maximum:", np.argmax(marks))
print("Index of Minimum:", np.argmin(marks))

print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

Original Array: [65 78 92 71 85 96 80]
Sorted Array: [65 71 78 80 85 92 96]

Sum: 567
Mean: 81.0
Median: 80.0
Maximum: 96
Minimum: 65
Range: 31
Standard Deviation: 10.198039027185569
Variance: 104.0
Index of Maximum: 5
Index of Minimum: 0
25th Percentile: 74.5
50th Percentile: 80.0
75th Percentile: 88.5


In [30]:
import numpy as np

# Random number
print(np.random.rand())

# Random numbers
print(np.random.rand(4))

# Random integers
print(np.random.randint(5, 21, 4))

# Random choice
subjects = ["C", "C++", "HTML", "AI"]
print(np.random.choice(subjects))

# Normal distribution
print(np.random.normal(60, 8, 4))

# Uniform distribution
print(np.random.uniform(20, 30, 4))

# Bernoulli random variable
print(np.random.binomial(1, 0.6))

# Binomial random variable
print(np.random.binomial(8, 0.8))

# Poisson random variable
print(np.random.poisson(5, 4))

# Exponential random variable
print(np.random.exponential(3, 4))

0.3320237122553089
[0.41204258 0.46275717 0.69185592 0.41233649]
[12 20  6 16]
C
[54.40259351 65.19324624 71.97656389 45.96398336]
[20.38112192 22.21285736 25.05775227 27.45886643]
0
8
[4 6 9 5]
[1.95566425 3.26131634 2.26563778 2.39997874]
