In [6]:
import numpy as np
arr = np.array([10, 20,30,40])
print(arr)

[10 20 30 40]


In [9]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)
print(arr.size)

(2, 3)
6


In [12]:
arr=np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [20]:
arr=np.arange(1,13)
print(arr.reshape(4,3))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
arr=np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [23]:
arr=np.full((3,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [25]:
arr=np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
arr = np.array([[10, 20, 30],[40, 50, 60]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

(2, 3)
2
6
int64
[[10 40]
 [20 50]
 [30 60]]


In [27]:
arr_3d = np.array([1,2,3,4,5,6,7,8])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[2:])
print(arr[::2])

[20 30 40 50]
[10 20 30 40]
[30 40 50 60]
[10 30 50]


In [31]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [37]:
arr=np.array([4,9,16,25,36])
print(np.sqrt(arr))
print(np.square(arr))
print(np.cos(90))
print(np.sin(90))
print(np.ceil(arr))
print(np.absolute(arr))
print(np.floor(arr))
print(np.power(4,3))

[2. 3. 4. 5. 6.]
[  16   81  256  625 1296]
-0.4480736161291701
0.8939966636005579
[ 4.  9. 16. 25. 36.]
[ 4  9 16 25 36]
[ 4.  9. 16. 25. 36.]
64


In [43]:
import numpy as np

v = np.array([2, 5, 1])
print(v)

M = np.array([[1, 2], [3, 4]])
print(M)

T = np.ones((3, 2, 2))
print(T)

[2 5 1]
[[1 2]
 [3 4]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [47]:
import numpy as np

a = np.array([1, 2, 3])

b = np.array([4, 0, 1])

np.dot(a, b)

#np.cross(a, b)

#np.linalg.norm(a)

#np.linalg.norm(a, 1)

#cos = a@b/(norm(a)*norm(b))

np.int64(7)

In [50]:
A = np.array([[2., 1.], [1., 3.]])

A.T # transpose

np.linalg.inv(A) # inverse

np.trace(A) # sum of diagonal = 5

np.allclose(A, A.T) # symmetric?



True

In [52]:
theta = np.radians(25)
point=np.sin(theta), np.cos(theta)


R = np.array([[np.cos(theta), -np.sin(theta)],

[np.sin(theta), np.cos(theta)]])

R @ point # rotate a point about the origin

array([4.26891359e-18, 1.00000000e+00])